name: legalease
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Core Python ---
  - python=3.12.11
  - pip
  - numpy
  - pandas
  - requests
  - ipykernel
  - jupyter_client
  - jupyter_core
  - setuptools
  - wheel
  - typing_extensions
  - pytz
  - ca-certificates
  - certifi
  - openssl
  - zlib
  - xz

  # --- Common scientific libs ---
  - asttokens=3.0.0
  - colorama=0.4.6
  - matplotlib-inline=0.1.7
  - networkx=3.5
  - pillow=11.1.0
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - sympy=1.13.1
  - yaml=0.2.5
  - zstd=1.5.7

  # --- Pip packages ---
  - pip:
      # --- Fixed Torch stack (CPU-only build) ---
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1

      # --- App / ML / Streamlit deps ---
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.68.0
      - anyio==4.10.0
      - attrs==25.3.0
      - azure-common==1.1.28
      - azure-core==1.35.1
      - azure-search-documents==11.5.3
      - bert-score==0.3.13
      - blinker==1.9.0
      - brotli==1.1.0
      - cachetools==6.2.0
      - click==8.2.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.1.1
      - dill==0.4.0
      - docstring-parser==0.17.0
      - evaluate==0.4.6
      - fastapi==0.117.1
      - ffmpy==0.6.1
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.183.0
      - google-auth==2.41.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - gradio==5.47.2
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - isodate==0.7.2
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - multidict==6.6.4
      - multiprocess==0.70.16
      - narwhals==2.5.0
      - nltk==3.9.1
      - openai==1.109.1
      - orjson==3.11.3
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pydub==0.25.1
      - pymupdf==1.26.4
      - pyparsing==3.2.4
      - pyphen==0.17.2
      - pytesseract==0.3.13
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - referencing==0.36.2
      - regex==2025.9.1
      - rich==14.1.0
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - rsa==4.9.1
      - ruff==0.13.2
      - sacremoses==0.1.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.48.0
      - streamlit==1.49.1
      - tenacity==9.1.2
      - textstat==0.7.10
      - threadpoolctl==3.6.0
      - tokenizers==0.22.0
      - toml==0.10.2
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - transformers==4.56.1
      - typer==0.19.2
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - uvicorn==0.37.0
      - watchdog==6.0.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.20.1
