# .streamlit/secrets.toml

ANTHROPIC_API_KEY = "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"
OPENAI_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyBAsdgDAGd9p-UQgTny6WUpeoStpyNsUtI"